"""PostgreSQL-backed hash index (psycopg, JSONB metadata)."""

from __future__ import annotations

import json
import logging
import threading
from collections.abc import Iterable

from ..exceptions import MissingDependencyError
from ..models import (
    Fingerprint,
    IndexPosting,
)
from ._common import (
    SNAPSHOT_FORMAT_VERSION_KEY,
    _index_metadata,
    _synchronized,
)
from .base import HashIndex

logger = logging.getLogger(__name__)


class PostgresHashIndex(HashIndex):
    """PostgreSQL-backed hash index for a shared, durable, server-grade store.

    Implements the same :class:`HashIndex` contract and inherits the shared
    ``search``/``save``/``load_snapshot``. Pass a ``dsn`` (libpq connection
    string) or inject a ``psycopg`` connection. ``psycopg`` is imported lazily, so
    importing this module never requires it.

    Storage layout (internal, output-preserving): mirroring SQLite, the
    ``files`` table maps each ``file_id`` to a small ``BIGINT`` surrogate id
    (``GENERATED BY DEFAULT AS IDENTITY``), and each posting stores that integer
    ``file_ref`` foreign key rather than the 64-char ``file_id`` string. Every
    read JOINs ``postings`` to ``files`` to recover the original ``file_id``, so
    :meth:`search`, :meth:`to_dict`, :meth:`list_files`, :meth:`query`,
    :meth:`query_many`, the counts, and cross-backend parity are BYTE-IDENTICAL to
    storing the string verbatim. ``postings`` is indexed on ``hash_code`` (fast
    ``query``) and ``file_ref`` (fast ``remove``/join). Metadata is ``JSONB``.

    Migration: a table set written by a PRIOR version of this class has the OLD
    schema (``postings.file_id TEXT``, ``files`` with no ``id`` column).
    :meth:`_init_schema` detects that and migrates it in place, transactionally,
    once on open (see :meth:`_migrate_legacy_schema_if_present`). This backend
    cannot be exercised in CI without a live server (it is gated behind
    ``@requires_pg``), so the migration here is implemented structurally to mirror
    the SQLite path that IS tested live.

    Like SQLite, PostgreSQL ``BIGINT`` is signed 64-bit, so unsigned 64-bit hash
    codes are stored with the same reversible signed offset.
    """

    _SIGNED_OFFSET = 1 << 63

    def __init__(
        self,
        dsn: str = "postgresql://localhost/fingerprint",
        connection=None,
        table_prefix: str = "fp",
    ) -> None:
        if not table_prefix.isidentifier():
            raise ValueError("table_prefix must be a valid SQL identifier")
        self._files_table = f"{table_prefix}_files"
        self._postings_table = f"{table_prefix}_postings"
        self._meta_table = f"{table_prefix}_meta"
        # Serializes the single shared psycopg connection (F3). A psycopg
        # connection is not safe for concurrent use across threads, so the FastAPI
        # threadpool sharing one active_index would otherwise race; mirroring the
        # SQLite backend, every connection-touching method holds this re-entrant
        # lock. Uncontended single-threaded, so output is byte-identical.
        self._lock = threading.RLock()
        if connection is not None:
            self._conn = connection
        else:
            try:
                import psycopg
            except ImportError as exc:  # pragma: no cover - exercised only without psycopg
                raise MissingDependencyError(
                    "psycopg is required for PostgresHashIndex; install with "
                    "'pip install \"fingerprint-engine[postgres]\"'",
                    package="psycopg",
                    extra="postgres",
                ) from exc
            self._conn = psycopg.connect(dsn)
        self._init_schema()

    def _init_schema(self) -> None:
        # Migrate an OLD-schema table set (postings.file_id TEXT, files without a
        # surrogate id) in place, once, before idempotently ensuring the new
        # tables/indexes below.
        self._migrate_legacy_schema_if_present()
        with self._conn.cursor() as cur:
            cur.execute(
                f"CREATE TABLE IF NOT EXISTS {self._files_table} ("
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                "file_id TEXT UNIQUE NOT NULL, metadata JSONB NOT NULL)"
            )
            cur.execute(
                f"CREATE TABLE IF NOT EXISTS {self._postings_table} ("
                "file_ref BIGINT NOT NULL, hash_code BIGINT NOT NULL, time_offset INTEGER NOT NULL)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS {self._postings_table}_hash_idx "
                f"ON {self._postings_table}(hash_code)"
            )
            cur.execute(
                f"CREATE INDEX IF NOT EXISTS {self._postings_table}_file_idx "
                f"ON {self._postings_table}(file_ref)"
            )
            # Side table recording the corpus hash-format version (F2): a row is
            # written only for a NON-default corpus, so a default store keeps an
            # empty meta and is byte-identical. Never read by to_dict/search.
            cur.execute(
                f"CREATE TABLE IF NOT EXISTS {self._meta_table} "
                "(key TEXT PRIMARY KEY, value TEXT NOT NULL)"
            )
            cur.execute(
                f"SELECT value FROM {self._meta_table} WHERE key = %s",
                (SNAPSHOT_FORMAT_VERSION_KEY,),
            )
            row = cur.fetchone()
        self._conn.commit()
        # Restore the durably-stored version (F2); absent -> unpinned default.
        if row is not None:
            self._load_persisted_format_version(row[0])

    def _persist_format_version(self, version: int) -> None:
        # F2: upsert the pinned (non-default) version into the side meta table so
        # a reopen restores it. Self-contained commit (only on first pin of a
        # non-default corpus) so it never leaves a dangling transaction.
        with self._lock:
            with self._conn.cursor() as cur:
                cur.execute(
                    f"INSERT INTO {self._meta_table} (key, value) VALUES (%s, %s) "
                    "ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value",
                    (SNAPSHOT_FORMAT_VERSION_KEY, str(version)),
                )
            self._conn.commit()

    def _migrate_legacy_schema_if_present(self) -> None:
        """One-time, transactional, in-place upgrade of an OLD-schema table set.

        Detects the pre-surrogate layout -- a ``postings`` table that HAS a
        ``file_id`` column and LACKS ``file_ref`` -- and rewrites it: a new
        ``files`` table with a ``BIGINT GENERATED ... AS IDENTITY`` surrogate id,
        populated from the distinct old file_ids; a new ``postings`` table whose
        ``file_ref`` is each posting's resolved surrogate; then drop the old
        tables and rename the new ones into place. Every file_id, metadata blob,
        and posting survives; the whole rewrite is one transaction, so a failure
        rolls back to the original old-schema tables. A fresh or already-migrated
        table set (no postings table, or one that already has ``file_ref``) is a
        no-op. Mirrors :meth:`SQLiteHashIndex._migrate_legacy_schema_if_present`;
        gated behind ``@requires_pg`` so it is not run live in CI.
        """

        with self._conn.cursor() as cur:
            cur.execute(
                "SELECT column_name FROM information_schema.columns WHERE table_name = %s",
                (self._postings_table,),
            )
            columns = {row[0] for row in cur.fetchall()}
        if not columns or "file_ref" in columns or "file_id" not in columns:
            self._conn.rollback()  # release the read txn; nothing to migrate
            return
        files_new = f"{self._files_table}_new"
        postings_new = f"{self._postings_table}_new"
        try:
            with self._conn.cursor() as cur:
                cur.execute(
                    f"CREATE TABLE {files_new} ("
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    "file_id TEXT UNIQUE NOT NULL, metadata JSONB NOT NULL)"
                )
                cur.execute(
                    f"CREATE TABLE {postings_new} ("
                    "file_ref BIGINT NOT NULL, hash_code BIGINT NOT NULL, time_offset INTEGER NOT NULL)"
                )
                # Identity ids are assigned as the distinct file_ids are inserted.
                cur.execute(
                    f"INSERT INTO {files_new} (file_id, metadata) "
                    f"SELECT file_id, metadata FROM {self._files_table}"
                )
                cur.execute(
                    f"INSERT INTO {postings_new} (file_ref, hash_code, time_offset) "
                    f"SELECT f.id, p.hash_code, p.time_offset "
                    f"FROM {self._postings_table} p JOIN {files_new} f ON f.file_id = p.file_id"
                )
                cur.execute(f"DROP TABLE {self._postings_table}")
                cur.execute(f"DROP TABLE {self._files_table}")
                cur.execute(f"ALTER TABLE {files_new} RENAME TO {self._files_table}")
                cur.execute(f"ALTER TABLE {postings_new} RENAME TO {self._postings_table}")
            self._conn.commit()
        except BaseException:
            self._conn.rollback()
            raise

    @classmethod
    def _encode(cls, hash_code: int) -> int:
        return int(hash_code) - cls._SIGNED_OFFSET

    @classmethod
    def _decode(cls, stored: int) -> int:
        return int(stored) + cls._SIGNED_OFFSET

    @property
    @_synchronized
    def file_count(self) -> int:
        try:
            with self._conn.cursor() as cur:
                cur.execute(f"SELECT COUNT(*) FROM {self._files_table}")
                count = int(cur.fetchone()[0])
        finally:
            self._conn.rollback()  # release the implicit read transaction even on error
        return count

    @property
    @_synchronized
    def posting_count(self) -> int:
        try:
            with self._conn.cursor() as cur:
                cur.execute(f"SELECT COUNT(*) FROM {self._postings_table}")
                count = int(cur.fetchone()[0])
        finally:
            self._conn.rollback()  # release the implicit read transaction even on error
        return count

    @_synchronized
    def add(self, fingerprint: Fingerprint) -> None:
        self._record_format_version(fingerprint)
        self.remove(fingerprint.file_id)
        metadata = _index_metadata(fingerprint)
        with self._conn.cursor() as cur:
            # remove() above deleted any prior files row, so RETURNING id yields a
            # fresh surrogate; postings carry that file_ref, not the file_id string.
            cur.execute(
                f"INSERT INTO {self._files_table} (file_id, metadata) "
                "VALUES (%s, %s::jsonb) RETURNING id",
                (fingerprint.file_id, json.dumps(metadata, sort_keys=True)),
            )
            file_ref = cur.fetchone()[0]
            cur.executemany(
                f"INSERT INTO {self._postings_table} (file_ref, hash_code, time_offset) "
                "VALUES (%s, %s, %s)",
                [
                    (file_ref, self._encode(item.hash_code), int(item.time_offset))
                    for item in fingerprint.hashes
                ],
            )
        self._conn.commit()

    @_synchronized
    def add_many(self, fingerprints: Iterable[Fingerprint]) -> None:
        """Ingest the whole batch in ONE transaction, streaming postings via COPY.

        Equivalent to per-item :meth:`add`: each ``file_id`` is removed before it
        is (re)inserted, so a duplicate ``file_id`` keeps only the LAST
        fingerprint and any pre-batch rows for it are deleted once -- identical
        postings, metadata, and search results. Postings stream through
        ``cursor.copy`` (PostgreSQL's bulk path, far faster than row-at-a-time
        INSERT); metadata goes via ``executemany``; everything commits once.
        """

        # Fail-closed PRE-CHECK (no pin/persist) so a cross-format batch raises
        # before any write OR version stamp -- true all-or-nothing (F1).
        fingerprints = list(fingerprints)
        self._validate_batch_format(fingerprints)
        # Last-wins per file_id (a sequential add() of a repeated id removes the
        # earlier copy), which also avoids the files PRIMARY KEY conflict.
        survivors: dict[str, Fingerprint] = {}
        for fingerprint in fingerprints:
            self._record_format_version(fingerprint)
            survivors[fingerprint.file_id] = fingerprint
        if not survivors:
            return

        # Per file: metadata blob plus encoded postings; the surrogate file_ref
        # is filled in once the files row is inserted and its id known.
        staged: list[tuple[str, str, list[tuple[int, int]]]] = []
        for file_id, fingerprint in survivors.items():
            metadata = _index_metadata(fingerprint)
            staged.append((
                file_id,
                json.dumps(metadata, sort_keys=True),
                [(self._encode(item.hash_code), int(item.time_offset)) for item in fingerprint.hashes],
            ))

        file_ids = list(survivors)
        try:
            with self._conn.cursor() as cur:
                # remove() effect for every target file_id (pre-batch rows):
                # postings are keyed by the surrogate, so delete by file_ref of
                # the existing rows, then drop the files rows.
                cur.execute(
                    f"DELETE FROM {self._postings_table} WHERE file_ref IN "
                    f"(SELECT id FROM {self._files_table} WHERE file_id = ANY(%s))",
                    (file_ids,),
                )
                cur.execute(
                    f"DELETE FROM {self._files_table} WHERE file_id = ANY(%s)", (file_ids,)
                )
                # Insert each files row, capturing its fresh surrogate id, then
                # stage that file's postings with the resolved file_ref.
                posting_rows: list[tuple[int, int, int]] = []
                for file_id, meta_json, encoded in staged:
                    cur.execute(
                        f"INSERT INTO {self._files_table} (file_id, metadata) "
                        "VALUES (%s, %s::jsonb) RETURNING id",
                        (file_id, meta_json),
                    )
                    file_ref = cur.fetchone()[0]
                    posting_rows.extend((file_ref, code, offset) for code, offset in encoded)
                if posting_rows:
                    with cur.copy(
                        f"COPY {self._postings_table} (file_ref, hash_code, time_offset) FROM STDIN"
                    ) as copy:
                        for row in posting_rows:
                            copy.write_row(row)
        except BaseException:
            self._conn.rollback()  # all-or-nothing; never leave a partial ingest
            raise
        self._conn.commit()

    @_synchronized
    def remove(self, file_id: str) -> None:
        with self._conn.cursor() as cur:
            # Postings are keyed by the surrogate; delete by the file's file_ref
            # (resolved via subselect), then drop the files row.
            cur.execute(
                f"DELETE FROM {self._postings_table} WHERE file_ref = "
                f"(SELECT id FROM {self._files_table} WHERE file_id = %s)",
                (file_id,),
            )
            cur.execute(f"DELETE FROM {self._files_table} WHERE file_id = %s", (file_id,))
        self._conn.commit()

    @_synchronized
    def query(self, hash_code: int) -> list[IndexPosting]:
        code = int(hash_code)
        try:
            with self._conn.cursor() as cur:
                # JOIN to files to recover the str file_id from the surrogate.
                cur.execute(
                    f"SELECT f.file_id, p.time_offset FROM {self._postings_table} p "
                    f"JOIN {self._files_table} f ON f.id = p.file_ref WHERE p.hash_code = %s",
                    (self._encode(code),),
                )
                rows = cur.fetchall()
        finally:
            self._conn.rollback()  # release the implicit read transaction even on error
        return [
            IndexPosting(file_id=row[0], hash_code=code, time_offset=int(row[1]))
            for row in rows
        ]

    @_synchronized
    def query_many(self, hash_codes: Iterable[int]) -> dict[int, list[IndexPosting]]:
        codes = list({int(c) for c in hash_codes})
        results: dict[int, list[IndexPosting]] = {code: [] for code in codes}
        if not codes:
            return results
        encoded = [self._encode(code) for code in codes]
        try:
            with self._conn.cursor() as cur:  # single round-trip via array membership
                # JOIN to files to map each posting's surrogate back to file_id.
                cur.execute(
                    f"SELECT p.hash_code, f.file_id, p.time_offset FROM {self._postings_table} p "
                    f"JOIN {self._files_table} f ON f.id = p.file_ref "
                    "WHERE p.hash_code = ANY(%s)",
                    (encoded,),
                )
                for stored, file_id, time_offset in cur.fetchall():
                    code = self._decode(stored)
                    results[code].append(
                        IndexPosting(file_id=file_id, hash_code=code, time_offset=int(time_offset))
                    )
        finally:
            self._conn.rollback()  # release the implicit read transaction even on error
        return results

    @_synchronized
    def _aggregate(
        self,
        fingerprint: Fingerprint,
        offset_tolerance: int = 0,
        candidates: set[str] | None = None,
    ) -> dict[str, tuple[int, int, int, int]]:
        """Aggregate the offset histogram server-side in one round-trip.

        The query's (hash_code, offset) pairs are passed as two arrays and
        unnested into a derived table, joined to the postings, then grouped by
        (file_ref, delta) -- grouping on the small integer surrogate, not the
        64-char file_id. Only per-file aggregates return; the surrogate is
        resolved back to the original str ``file_id`` by a single JOIN to the
        files table in the final SELECT, so the result is keyed by the SAME
        ``file_id`` as every other backend.

        With ``offset_tolerance == 0`` (the default) the winning bin is picked
        server-side as votes DESC then delta ASC, matching the base in-memory
        tie-break -- unchanged and BYTE-IDENTICAL to before the option existed
        (partitioning by ``file_ref`` is a 1:1 relabelling of the file_id
        partitions, so the per-file winning row is unchanged). With ``> 0`` the
        compact per-(file, delta) histogram is returned and the banded winner is
        chosen by the shared :meth:`_banded_winner` so every backend bands
        identically.

        ``candidates`` is the OPT-IN prefilter set: ``None`` (the default) returns
        the aggregate for every matched file, byte-identical to before the
        prefilter existed; a set keeps only those ``file_id`` (filtered on the
        per-file aggregate rows, so a retained file's row is never altered), so a
        candidate superset of the true top-k yields the identical ranking.
        """

        if not fingerprint.hashes:
            return {}
        codes = [self._encode(h.hash_code) for h in fingerprint.hashes]
        offsets = [int(h.time_offset) for h in fingerprint.hashes]
        banded = offset_tolerance > 0
        if banded:
            sql = f"""
                WITH q(hash_code, qoff) AS (SELECT * FROM unnest(%s::bigint[], %s::int[])),
                matches AS (
                    SELECT p.file_ref AS file_ref, (p.time_offset - q.qoff) AS delta, p.hash_code AS hc
                    FROM {self._postings_table} p JOIN q ON p.hash_code = q.hash_code
                ),
                bins AS (SELECT file_ref, delta, COUNT(*) AS votes FROM matches GROUP BY file_ref, delta),
                totals AS (
                    SELECT file_ref, COUNT(*) AS total_votes, COUNT(DISTINCT hc) AS uniq
                    FROM matches GROUP BY file_ref
                )
                SELECT f.file_id, b.delta, b.votes, t.total_votes, t.uniq
                FROM bins b JOIN totals t ON b.file_ref = t.file_ref
                JOIN {self._files_table} f ON f.id = b.file_ref
                """
        else:
            sql = f"""
                WITH q(hash_code, qoff) AS (SELECT * FROM unnest(%s::bigint[], %s::int[])),
                matches AS (
                    SELECT p.file_ref AS file_ref, (p.time_offset - q.qoff) AS delta, p.hash_code AS hc
                    FROM {self._postings_table} p JOIN q ON p.hash_code = q.hash_code
                ),
                bins AS (SELECT file_ref, delta, COUNT(*) AS votes FROM matches GROUP BY file_ref, delta),
                ranked AS (
                    SELECT file_ref, delta, votes,
                           ROW_NUMBER() OVER (PARTITION BY file_ref ORDER BY votes DESC, delta ASC) AS rn
                    FROM bins
                ),
                totals AS (
                    SELECT file_ref, COUNT(*) AS total_votes, COUNT(DISTINCT hc) AS uniq
                    FROM matches GROUP BY file_ref
                )
                SELECT f.file_id, r.delta, r.votes, t.total_votes, t.uniq
                FROM ranked r JOIN totals t ON r.file_ref = t.file_ref
                JOIN {self._files_table} f ON f.id = r.file_ref
                WHERE r.rn = 1
                """
        try:
            with self._conn.cursor() as cur:
                cur.execute(sql, (codes, offsets))
                rows = cur.fetchall()
        finally:
            self._conn.rollback()  # release the implicit read transaction even on error
        if candidates is not None:
            rows = [row for row in rows if str(row[0]) in candidates]
        if banded:
            return self._reduce_banded_rows(rows, offset_tolerance)
        return {
            file_id: (int(delta), int(votes), int(total), int(uniq))
            for file_id, delta, votes, total, uniq in rows
        }

    @_synchronized
    def prune_stop_hashes(self, max_df_ratio: float = 0.1) -> int:
        file_total = self.file_count
        if file_total == 0:
            return 0
        threshold = max_df_ratio * file_total
        posts, files = self._postings_table, self._files_table
        with self._conn.cursor() as cur:
            # Document frequency is distinct surrogates touching a code (1:1 with
            # distinct file_ids), so COUNT(DISTINCT file_ref) is the same df test.
            cur.execute(
                f"DELETE FROM {posts} WHERE hash_code IN ("
                f"  SELECT hash_code FROM {posts} GROUP BY hash_code "
                f"  HAVING COUNT(DISTINCT file_ref) > %s)",
                (threshold,),
            )
            removed = cur.rowcount
            if removed:
                # Recalibrate stored hash_count to remaining postings per file,
                # joining the surrogate-keyed counts back to files by id.
                cur.execute(
                    f"UPDATE {files} f SET metadata = "
                    f"jsonb_set(f.metadata, '{{hash_count}}', to_jsonb(c.cnt)) "
                    f"FROM (SELECT file_ref, COUNT(*) AS cnt FROM {posts} GROUP BY file_ref) c "
                    f"WHERE f.id = c.file_ref"
                )
                cur.execute(
                    f"UPDATE {files} SET metadata = jsonb_set(metadata, '{{hash_count}}', '0'::jsonb) "
                    f"WHERE id NOT IN (SELECT DISTINCT file_ref FROM {posts})"
                )
        self._conn.commit()
        return removed

    @_synchronized
    def _metadata_for(self, file_id: str) -> dict:
        try:
            with self._conn.cursor() as cur:
                cur.execute(
                    f"SELECT metadata FROM {self._files_table} WHERE file_id = %s", (file_id,)
                )
                row = cur.fetchone()
        finally:
            self._conn.rollback()  # release the implicit read transaction even on error
        if not row:
            return {}
        data = row[0]
        if isinstance(data, str):  # some drivers return JSONB as text
            try:
                data = json.loads(data)
            except (ValueError, TypeError):
                return {}
        return data if isinstance(data, dict) else {}

    @_synchronized
    def list_files(self) -> list[str]:
        try:
            with self._conn.cursor() as cur:
                # ORDER BY file_id matches the base sorted() contract server-side.
                cur.execute(f"SELECT file_id FROM {self._files_table} ORDER BY file_id")
                file_ids = [row[0] for row in cur.fetchall()]
        finally:
            self._conn.rollback()  # release the implicit read transaction even on error
        return file_ids

    @_synchronized
    def contains(self, file_id: str) -> bool:
        try:
            with self._conn.cursor() as cur:
                cur.execute(
                    f"SELECT 1 FROM {self._files_table} WHERE file_id = %s LIMIT 1", (file_id,)
                )
                row = cur.fetchone()
        finally:
            self._conn.rollback()  # release the implicit read transaction even on error
        return row is not None

    @_synchronized
    def to_dict(self) -> dict[str, object]:
        files: dict[str, list[list[int]]] = {}
        metadata: dict[str, dict] = {}
        try:
            with self._conn.cursor() as cur:
                # Carry the surrogate id so postings can be read by file_ref; the
                # ORDER BY hash_code, time_offset is preserved so per-file posting
                # order is byte-identical to before.
                cur.execute(f"SELECT id, file_id FROM {self._files_table}")
                file_rows = cur.fetchall()
            for file_ref, file_id in file_rows:
                with self._conn.cursor() as cur:
                    cur.execute(
                        f"SELECT hash_code, time_offset FROM {self._postings_table} "
                        "WHERE file_ref = %s ORDER BY hash_code, time_offset",
                        (file_ref,),
                    )
                    files[file_id] = [
                        [self._decode(hash_code), int(time_offset)]
                        for hash_code, time_offset in cur.fetchall()
                    ]
                metadata[file_id] = self._metadata_for(file_id)
        finally:
            # Even an EMPTY index (only the file_id SELECT runs, no per-file
            # reads that would roll back) must not leave the connection
            # idle-in-transaction holding a snapshot.
            self._conn.rollback()
        return {"backend": "postgres", "files": files, "metadata": metadata}

    def close(self) -> None:
        self._conn.close()

    def __enter__(self) -> PostgresHashIndex:
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()
